output-destination: /home/thomas/Work/Research/uil/macro_energy/data/
data-sources:
  san-fransisco:
    energy:
      description: "https://data.sfgov.org/Energy-and-Environment/Existing-Buildings-Energy-Performance-Ordinance-Re/j2j3-acqj"
      download: "https://data.sfgov.org/api/views/j2j3-acqj/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 1.5
    footprints:
      description: ""
      download: "https://data.sfgov.org/api/geospatial/ynuv-fyni?method=export&format=GeoJSON"
      filetype: "geojson"
      filesize: 320
  new-york:
    energy-2021:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/7x5e-2fxh"
      download: "https://data.cityofnewyork.us/api/views/7x5e-2fxh/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 86
    energy-2020:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/usc3-8zwd"
      download: "https://data.cityofnewyork.us/api/views/usc3-8zwd/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 80
    energy-2019:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/wcm8-aq5w"
      download: "https://data.cityofnewyork.us/api/views/wcm8-aq5w/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 84
    energy-2018:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/4tys-3tzj"
      download: "https://data.cityofnewyork.us/api/views/4tys-3tzj/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 74
    energy-2017:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/4t62-jm4m"
      download: "https://data.cityofnewyork.us/api/views/4t62-jm4m/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 33
    energy-2016:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/utpj-74fz"
      download: "https://data.cityofnewyork.us/api/views/utpj-74fz/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 49
    energy-2015:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/77q4-nkfh"
      download: "https://data.cityofnewyork.us/api/views/77q4-nkfh/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 48
    energy-2014:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/nbun-wekj"
      download: "https://data.cityofnewyork.us/api/views/nbun-wekj/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 38
    energy-2013:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/yr5p-wjer"
      download: "https://data.cityofnewyork.us/api/views/yr5p-wjer/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 51
    energy-2012:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/r6ub-zhff"
      download: "https://data.cityofnewyork.us/api/views/r6ub-zhff/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 34
    energy-2011:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/k7nh-aufb"
      download: "https://data.cityofnewyork.us/api/views/k7nh-aufb/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 10
    energy-2010:
      description: "https://data.cityofnewyork.us/Environment/Energy-and-Water-Data-Disclosure-for-Local-Law-84-/kswi-37bp"
      download: "https://data.cityofnewyork.us/api/views/kswi-37bp/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 5.6
    footprints:
      description: "https://github.com/CityOfNewYork/nyc-geo-metadata/blob/master/Metadata/Metadata_BuildingFootprints.md"
      download: "https://data.cityofnewyork.us/api/geospatial/qb5r-6dgf?method=export&format=GeoJSON"
      filetype: "geojson"
      filesize: 398
  austin:
    energy:
      description: "https://data.austintexas.gov/Utilities-and-City-Services/2019-Multifamily-ECAD/feiy-7jhe"
      download: "https://data.austintexas.gov/api/views/feiy-7jhe/rows.csv?accessType=DOWNLOAD"
      filetype: "csv"
      filesize: 50
    footprints:
      description: "https://data.austintexas.gov/dataset/Building-Footprints-Year-2013/3qcc-8uhz"
      download: "https://data.austintexas.gov/api/geospatial/3qcc-8uhz?accessType=DOWNLOAD&method=export&format=GeoJSON"
      filetype: "geojson"
      filesize: 423
